---
title: "Course Schedule"
tbl-colwidths: [5,15,30,5,5,5,5,15]
editor: visual
---

```{r setup, include = FALSE}
library(lubridate)

mon <- as_date("2024-08-26")
wed <- mon+days(2)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  # Extract day of the week and calendar date
  dow <- wday(date, label = TRUE, abbr = TRUE)  # Get day of the week
  dm <- paste(month(date, label = TRUE)," ",day(date))
  return(paste0(dow, ", ", dm))
}
```

This page displays an outline of the topics, content, and assignments
for the semester. Slides and assignment links will go live as the
semester progresses. ***All assignments must be submitted by 11:59 p.m.
on the due date***.

::: column-screen-inset-right
| Week | Date                | Topic                           | Reading |                       Video                       | Slides | Assignment | Due Date |
|:-------:|----------|---------|:-------:|:-------:|:-------:|---------|:-------:|
|  1   | `r advdate(mon,0)`  | Welcome to DATS 1001            |         |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,0)`  | Meet ouR tech stack             |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|  2   | `r advdate(mon,1)`  | ðŸ‡ºðŸ‡¸ No class, Labor Day          |         |                                                   |        |            |          |
|      | `r advdate(wed,1)`  | Grammar of graphics             |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|  3   | `r advdate(mon,2)`  | Categorical and continuous data |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,2)`  | Visualization best practices    |   ðŸ“–    | [ðŸ“º](https://www.youtube.com/watch?v=y7ESq_O3Odw) |   ðŸ–¥ï¸   |            |    ðŸ§®    |
|  4   | `r advdate(mon,3)`  | What is tidy data?              |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,3)`  | Grammar of data wrangling       |         |                                                   |   ðŸ–¥ï¸   |            |    ðŸ“˜    |
|  5   | `r advdate(mon,4)`  | Joining data                    |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,4)`  | Tidying data                    |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|  6   | `r advdate(mon,5)`  |                                 |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,5)`  |                                 |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |          |
|  7   | `r advdate(mon,6)`  |                                 |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,6)`  |                                 |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |    ðŸ§®    |
|  8   | `r advdate(mon,7)`  |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,7)`  |                                 |         |                                                   |   ðŸ–¥ï¸   |            |    ðŸ“˜    |
|  9   | `r advdate(mon,8)`  |                                 |   ðŸ“–    |                                                   |        |            |          |
|      | `r advdate(wed,8)`  |                                 |         |                                                   |        |            |          |
|  10  | `r advdate(mon,9)`  |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,9)`  |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |    âœï¸    |
|  11  | `r advdate(mon,10)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,10)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|  12  | `r advdate(mon,11)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,11)` |                                 |   ðŸ“–    |                        ðŸ“º                         |   ðŸ–¥ï¸   |            |    âœï¸    |
|  13  | `r advdate(mon,12)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,12)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|  14  | `r advdate(mon,13)` |                                 |   ðŸ“–    |                                                   |   ðŸ–¥ï¸   |            |          |
|      | `r advdate(wed,13)` |                                 |         |                                                   |        |            |          |
|  15  | `r advdate(mon,14)` |                                 |         |                        ðŸ“º                         |        |            |          |
|      | `r advdate(wed,14)` |                                 |         |                                                   |        |            |  ðŸ“˜ âœï¸   |
:::
